services:

  database:
    image: postgres:16
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: TaskManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: taskmanager-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: Host=database;Port=5432;Database=TaskManager;Username=postgres;Password=123

    depends_on:
      - database

volumes:
  postgres_data: