// <auto-generated />
using System;
using MVP_TaskManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVP_TaskManager.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    partial class TaskManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_role", new[] { "admin", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVP_TaskManager.Models.StatusRef", b =>
                {
                    b.Property<int>("IdStatus")
                        .HasColumnType("integer")
                        .HasColumnName("id_status");

                    b.Property<string>("NameStatus")
                        .HasColumnType("text")
                        .HasColumnName("name_status");

                    b.HasKey("IdStatus")
                        .HasName("status_ref_pkey");

                    b.ToTable("status_ref", (string)null);
                });

            modelBuilder.Entity("MVP_TaskManager.Models.Task", b =>
                {
                    b.Property<int>("IdTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_task");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTask"));

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdStatus")
                        .HasColumnType("integer")
                        .HasColumnName("id_status");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("IdTask")
                        .HasName("tasks_pkey");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdUser");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("MVP_TaskManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateOnly?>("RegDate")
                        .HasColumnType("date")
                        .HasColumnName("reg_date");

                    b.Property<int>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MVP_TaskManager.Models.Task", b =>
                {
                    b.HasOne("MVP_TaskManager.Models.StatusRef", "IdStatusNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("IdStatus")
                        .HasConstraintName("fk_id_status");

                    b.HasOne("MVP_TaskManager.Models.User", "IdUserNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("fk_id_user");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MVP_TaskManager.Models.StatusRef", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("MVP_TaskManager.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
